### ISSUE TITLE
[Optimization] If castData.author.pfp_url is null,  a default avatar should be displayed or controlled from props.

### ISSUE THREAD

**Issue by linrz** [neynarxyz/react#10]
If `castData.author.pfp_url ` is null, the render result is `<img alt="null Avatar" />`, can we optimize it and set it to be the same as the default avatar of [warpcast](https://warpcast.com/)? Or allow developers to control it from component props.

**Comment by dylsteck** [comment]
Hey @linrz, thanks for creating this issue! We have an active fix for this bug and should have better resolution for `castData.author.pfp_url` being null or blank in the future.

**Comment by dylsteck** [comment]
Hey @linrz! I wanted to circle back and let you know that [our latest release(v0.6.0)](https://github.com/neynarxyz/react/releases/tag/v0.6.0) solves this problem by falling back to a skeleton pfp if there isn't a valid value at `castData.author.pfp_url`.
